Parts 1-4
SleepyUser/chessington-ts pull request #1
Opened 2023-10-19 11:22 UTC by SleepyUser

Pawns movement, Rook Movement, Bishops movement.

(I realised the code wasn't formatted and I've formatted them all in my current branch, had an issue with my email being on the commits, so I had to squash them once I'd updated my git email to get rid of it)

2023-10-19 16:11 UTC, kwunkiuma requested changes
Looks good! Just some small suggestions 😄 

Opening braces on newlines is more of a C/C# convention. In TypeScript we tend to do it at the end of the same line 🙂

Real projects will have auto-formatters set up so it generally doesn't need any attention paid to it

2023-10-19 16:11 UTC, kwunkiuma commented on src/engine/pieces/bishop.ts
> +        let availableSquares: Square[] =[];
This `availableSquares` can be a const! Calling push on arrays doesn't tend to count as modifying them 🙂

You should be able to update the other usages to const too!

2023-10-19 16:11 UTC, kwunkiuma commented on src/engine/pieces/bishop.ts
> +        for (let i = 1; Math.max(square.col +i, square.row + i) <= 7; i++)
We should be able to use && for these two conditionals too, I think that's slightly better than using max/min 🙂

2023-10-20 08:37 UTC, SleepyUser commented on src/engine/pieces/bishop.ts
> +        let availableSquares: Square[] =[];
I believe I got them all :)

2023-10-20 08:38 UTC, SleepyUser commented
> Looks good! Just some small suggestions 😄
> 
> Opening braces on newlines is more of a C/C# convention. In TypeScript we tend to do it at the end of the same line 🙂
> 
> Real projects will have auto-formatters set up so it generally doesn't need any attention paid to it

I realised this right after I got into doing the next branch, as I had the "auto format when commit" turned on in FizzBuzz. In all the branches after this one I've turned that on again, so it will be fixed in the next PR.

2023-10-20 10:00 UTC, kwunkiuma approved these changes
LGTM, thanks!

2023-10-20 10:34 UTC, merged